configuration:
  - Debug
  - Release

environment:
  matrix:
    - generator: "Visual Studio 12 2013 Win64"
    - generator: "Visual Studio 12 2013"
    - generator: "Visual Studio 14 2015 Win64"
    - generator: "Visual Studio 14 2015"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      generator: "Visual Studio 15 2017 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      generator: "Visual Studio 15 2017"

matrix:
  fast_finish: true
  
shallow_clone: true

before_build:
  - cmake . -Bbuild -G"%generator%"

build_script:
  - set CMAKE_BUILD_FLAGS=--config %configuration% -- /m /v:m
  - cmake --build build %CMAKE_BUILD_FLAGS%
  